name: .NET Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore TimeScaleAPI.UnitTests/TimeScaleAPI.UnitTests.sln

    - name: Build solution
      run: dotnet build TimeScaleAPI.UnitTests/TimeScaleAPI.UnitTests.sln --configuration Release --no-restore

    - name: Run tests with coverage
      run: |
        dotnet test TimeScaleAPI.UnitTests/TimeScaleAPI.UnitTests.sln \
          --configuration Release \
          --no-build \
          --collect:"XPlat Code Coverage"

    - name: Install reportgenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Convert coverage to lcov
      run: |
        reportgenerator \
          -reports:**/coverage.cobertura.xml \
          -targetdir:coverage \
          -reporttypes:lcov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ./coverage/lcov.info
        token: ${{ secrets.CODECOV_TOKEN }}